include:
  - local: '/ci/abstract_jobs.yml'
  - local: '/ci/ci-config.yml'

stages:
  - build_docker_images
  - build_and_source_test
  - built_test_and_deploy
  - deploy

workflow:
  rules:
    - if: $RUN_CI_PIPELINE == "false"
      when: never
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /(^feat)|(^pu)|(change)/
      when: never
    - when: always

# ============ stage: build_docker_images ===========================
# This stage should produce everything needed to run source test (jenkins like test, on the source code with webpack).

"docker: build base, dependency, source and test-source image":
  extends: .abstract_jobs.docker
  stage: build_docker_images
  script:
    - cp $DOCKER_GIT_CONFIG ./ci/dockerimage/.gitconfig
    - build_image base
    - use_cached_image_when_nothing_changed base
    - push_image base
    - build_image source
    - use_cached_image_when_nothing_changed source
    - push_image source
    - build_image test-source
    - push_image test-source
  timeout: 60m

# ============ stage: build_and_source_test ===========================
# This stage runs source tests. This are all test which do not require a js build.
# This stage builds all the docker image the were not build in the first stage.
# The base-commit, source-commit, source-test-commit images are available here.
# They are named according to $REGISTRY/$NAME-commit:$CI_PIPELINE_ID-$PHP_IMAGE_TAG

"php unit: all tests source":
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-source-commit
    NODE_TOTAL: 1
    NODE_INDEX: 1
  stage: build_and_source_test
  timeout: 45m
  rules:
    - if: $RUN_ALL_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_PARALLEL == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
      when: on_success
    - when: never

"php unit: all tests source, parallel":
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-source-commit
  stage: build_and_source_test
  timeout: 45m
  parallel: 5
  rules:
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_PARALLEL == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
      when: on_success
    - when: never

"php unit: servertests source":
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-source-commit
    ARG_TEST: AllServerTests
  stage: build_and_source_test
  timeout: 30m
  rules:
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_SERVERTESTS == "true"
      when: on_success
    - when: never

"php unit: setup tests source":
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-source-commit
    ARG_TEST_PATH_FROM_TINE20ROOT: tests/setup/
  stage: build_and_source_test
  timeout: 30m
  rules:
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_SETUP_TESTS == "true"
      when: on_success
    - changes:
        - tine20/Setup/**/*
    - when: never

"phpstan: code analyses":
  stage: build_and_source_test
  image:
    name: "$REGISTRY/test-source-commit:$CI_PIPELINE_ID-$PHP_IMAGE_TAG"
  script:
    - cd $TINE20ROOT
    - composer require phpstan/phpstan
    - php -d memory_limit=2G $TINE20ROOT/vendor/bin/phpstan analyse --autoload-file=$TINE20ROOT/tine20/vendor/autoload.php --error-format=prettyJson --no-progress -vvv | tee $CI_PROJECT_DIR/code-quality-report.json
  artifacts:
    reports:
      codequality: code-quality-report.json
    paths:
      - code-quality-report.json
    expire_in: 1 days
  rules:
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_STAN_ANALYSES == "true"
      when: on_success
    - when: never
  allow_failure: true
  timeout: 20m # time run: 4m

"docker: build dev, built and test-built image":
  extends: .abstract_jobs.docker
  stage: build_and_source_test
  script:
    - build_image build
    - use_cached_image_when_nothing_changed build
    - build_image built
    - use_cached_image_when_nothing_changed built
    - push_image build
    - push_image built
    - build_image test-built
    - push_image test-built
    - build_image dev
    - use_cached_image_when_nothing_changed dev
    - push_image dev
  rules:
    - if: $DOCKER_BUILD_BUILD == "true"
      when: on_success
    - when: never
  timeout: 60m # time run: 28m

# ============ stage: built_test_and_deploy ===========================
# Run all test which require a js build.
# And push all images already tested.

"php unit: all tests built":
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-built-commit
  stage: built_test_and_deploy
  parallel: 5
  timeout: 45m
  rules:
    - if: $RUN_ALL_TESTS == "true"
      when: always
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "true"
      when: on_success
    - when: never

"php unit: nogitlabci tests built":
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-built-commit
    ARG_EXCLUDE_GROUP: ""
    ARG_GROUP: "nogitlabci"
  stage: built_test_and_deploy
  parallel: 5
  allow_failure: true
  timeout: 30m
  rules:
    - if: $RUN_ALL_TESTS == "true"
      when: always
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "true"
      when: on_success
    - when: never

"php unit: all tests built with ldap":
  extends: .abstract_jobs.php_unit_ldap
  variables:
    ARG_IMAGE: test-built-commit
  stage: built_test_and_deploy
  parallel: 5
  timeout: 30m
  rules:
    - if: $RUN_ALL_TESTS == "true"
      when: always
    - if: $PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP == "true"
      when: on_success
    - when: never

# Pushes base-commit as base, source-commit as source and test-source-commit as test-source to aws ecr.
# They are used for caching.
# Only images which passed the source test are pushed.
# The ecr registry is vital for the ci. So this is more an internal push.
"docker: push base, source, test-source and dependency image":
  extends: .abstract_jobs.docker
  stage: built_test_and_deploy
  script:
    - tag_commit_as_branch_image base
    - tag_commit_as_branch_image source
    - tag_commit_as_branch_image test-source
  rules:
    - if: $RUN_ALL_TESTS == "true"
      when: never
    - if: $NO_PUSH == "true"
      when: never
    - when: on_success
  timeout: 20m # time run: 3m

# ============ stage: deploy ===========================

# Pushes build-commit as build, built-commit as built and test-built-commit as test-built and dev-commit as dev to aws ecr.
# They are used for caching.
# Only images which passed the built test are pushed.
# The ecr registry is vital for the ci. So this is more an internal push.
"docker: push built, build, test-build and dev image":
  extends: .abstract_jobs.docker
  stage: deploy
  script:
    - tag_commit_as_branch_image built
    - tag_commit_as_branch_image dev
    - tag_commit_as_branch_image build
    - tag_commit_as_branch_image test-built
  rules:
    - if: $RUN_ALL_TESTS == "true"
      when: never
    - if: $NO_PUSH == "true"
      when: never
    - if: $DOCKER_BUILD_BUILD == "true"
      when: on_success
    - when: never
  timeout: 20m # time run: 3m

# pushes built-commit as built and dev-commit as dev to our gitlab registry.
# They can be accessed essayer.
# They are pushed on every change of a major branch.
"docker push built and dev image to gitlab":
  extends: .abstract_jobs.docker
  stage: deploy
  script:
    - tag_commit_as_gitlab_image built
    - tag_commit_as_gitlab_image dev
  rules:
    - if: $RUN_ALL_TESTS == "true"
      when: never
    - if: $NO_PUSH == "true"
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /(^feat)|(^pu)|(change)/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $DOCKER_BUILD_BUILD == "true"
      when: on_success
    - when: never
  timeout: 20m

# pushing built-commit as tine20/tine20 and dev as tine20/dev to dockerhub.
# The tag is also overwritten and set to $DOCKERHUB_TAG
# This job should only be triggered by a schedule or a manual pipeline trigger
"docker push built image to dockerhub":
  extends: .abstract_jobs.docker
  stage: deploy
  script:
    - tag_commit_as_dockerhub_image built tine20
    - tag_commit_as_dockerhub_image dev dev
  rules:
    - if: $RUN_ALL_TESTS == "true"
      when: never
    - if: $NO_PUSH == "true"
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /(^feat)|(^pu)|(change)/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $DOCKER_BUILD_BUILD != "true"
      when: never
    - if: $PUSH_TO_DOCKERHUB == "true"
      when: on_success
    - when: never
  timeout: 20m