---
vagrantfile-local:
    vm:
        box: debian-wheezy72-x64-vbox43
        box_url: 'http://box.puphpet.com/debian-wheezy72-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.56.101
            forwarded_port: {  }
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            LZhss9UMsFXn:
                id: vagrant-root
                source: ./
                target: /var/www
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: ':detect'
server:
    packages: {  }
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
apache:
    modules:
        - php
        - rewrite
    vhosts:
        dYDR07tVlxGd:
            servername: tine.vagrant
            serveraliases:
                - tine.vagrant
            docroot: /www/tine.vagrant/htdocs
            port: '80'
            setenv:
                - 'APP_ENV dev'
            additional_includes:
                - /vagrant/puphpet/files/dot/apache.conf
    user: www-data
    group: www-data
    default_vhost: true
    mpm_module: prefork
    mod_pagespeed: 0
    mod_spdy: 0
php:
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - xsl
            - ldap
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/Chicago
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '1'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    root_password: '1234'
    phpmyadmin: '1'
    adminer: 0
    databases: {  }
beanstalkd:
    install: 0
    listenaddress: 0.0.0.0
    listenport: '13000'
    maxjobsize: '65535'
    maxconnections: '1024'
    binlogdir: /var/lib/beanstalkd/binlog
    binlogfsync: null
    binlogsize: '10485760'

