variables:
  PHP_UNIT_ALL_TESTS_SOURCE: "true"
  PHP_UNIT_ALL_TESTS_BUILT: "true"
  PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP: "false"
  MAJOR_COMMIT_REF_NAME: "2018.11"
  DOCKER_BUILD_BUILD: "true"
  DOCKER_RETAG_PHP_IMAGE: "false"
  PHP_STAN_ANALYSES: "true"
  NO_CACHE: "false"