# overwritten by: ci-config.yml < variables in gitlab-ci.yml < gitlab project variables < per pipeline variables
variables:
  MAJOR_COMMIT_REF_NAME:
    description: "The major commit ref name is mainly used for ci caching. Non feature branches should be there own major. The major of feature branches should be the branch the will be merged into."
    value: "2020.11"

  # General
  # "Docker hub tag for this build."
  DOCKERHUB_TAG: "dev"

  # "Install one custom app via composer: vendor"
  CUSTOM_APP_VENDOR: "metaways"

  # "Install one custom "dev-master"

  # install one custom app via composer: name
  # CUSTOM_APP_NAME default should be nothing

  # install one custom app via composer: git url
  # CUSTOM_APP_GIT_URL default should be nothing

  # "Select e2e test to run. - npm test $JS_E2E_TEST_FILTER"
  JS_E2E_TEST_FILTER: ""

  # "Database image used by tests."
  DATABASE_IMAGE: "${UTIL_REGISTRY}/mariadb:10.4.1"

  # "Rdis image to use druing tests."
  REDIS_IMAGE: "${UTIL_REGISTRY}/redis:5.0.5"

  # "Add a php unit filter to all php unit test jobs e.g. CashBook. This is used for customapp tests."
  PHPUNIT_FILTER: ""
  
  # "Php version to use."
  PHP_VERSION: "7.4"

  # "Codename for build"
  CODENAME: "Amon"

  # "Try to reuse source images" 
  REUSE_IMAGES: "true"

  # "Build zip packages, wenn packaging. (Tar packages are always build)"
  ZIP_PACKAGES: "false"

  # "Rewrite composer lock to pull packages from cache."
  COMPOSER_LOCK_REWRITE: "true"

  # Test Jobs
  # Variable are swiched on with the string "true" and off with the string "false".
  # No test job must run if RUN_NO_TESTS is true.
  #
  # Every test job has an variable (uppercase(name)) which determents if it should run. These Should not be set in the ci config or project variables. 
  # They should strictly be used for pipeline triggert manualy or by api. Or for customising schedules.
  # For these vars applies true = always run, false = never run and "" = if some other rule matches
  #
  # Test Jobs also have variables uppercase(name)_MERGE_REQUEST and uppercase(name)_SCHEDULE which determit if it is run during the corospoding pipelines. 
  # They should only be set in the project variables, to temporaraly enable disable Jobs. If the job config should be changed permanantly the rules if should 
  # be switched: eg: $VAR == "false" => $VAR != "true"
  # For these vars applies true = run on eg. mr, false = dont run for eg. mr and "" = use default
  #
  # eg:
  # PHP_UNIT_ALL_TESTS_LDAP_BUILD: "false" # default is ""
  # PHP_UNIT_ALL_TESTS_LDAP_BUILD_MERGE_REQUEST: "true" # default is "false"
  # PHP_UNIT_ALL_TESTS_LDAP_BUILD_SCHEDULE: "false" # default is "true"

  PHPCS_ANALYSIS_STRICT: "true"
  PARALLEL_LINT_ANALYSIS_STRICT: "false"
  PHP_STAN_ANALYSES_STRICT: "false"
  PHP_UNIT_ALL_TESTS_SOURCE_TYPE: "parallel" #parallel, sequential, matrix
  PHP_UNIT_TESTS_SOURCE_POSTFIXMULTIINSTANCE_TYPE: "parallel" #parallel, sequential
  PHP_UNIT_ALL_TESTS_BUILT_TYPE: "parallel" #parallel, sequential
  PHP_UNIT_NOGITLABCI_TESTS_BUILT_TYPE: "parallel" #parallel, sequential
  PHP_UNIT_ALL_TESTS_LDAP_BUILD_TYPE: "parallel" #parallel, sequential

  # Deploy
  #
  # DEPLOY_BUILD_IMAGE_TO_GITLAB:
  #DEPLOY_BUILD_IMAGE_TO_GITLAB_SCHEDULE: "false"

  # DEPLOY_DEV_IMAGE_TO_GITLAB:
  #DEPLOY_DEV_IMAGE_TO_GITLAB_SCHEDULE: "false"

  # DEPLOY_IMAGES_TO_DOCKERHUB: