# This file sets the defaults for all ci variables.
# It can and should be used to configure differences between branches.
# It can also be used for feature branches e.g. if not all test are needed or another db should be used.
# overwritten by: ci-config.yml < variables in gitlab-ci.yml < gitlab project variables < per pipeline variables

variables:
  MAJOR_COMMIT_REF_NAME:
    description: "The major commit ref name is mainly used for ci caching. Non feature branches should be there own major. The major of feature branches should be the branch the will be merged into."
    value: "2020.11"

  RUN_CI_PIPELINE:
    description: "Main toggle for gitlab ci. If false the ci will do nothing. This results in a failed pipeline."
    value: "true"

  NO_PUSH:
    description: "Do not push any images. Commit images will still be pushed. Becouse they are needed for ci caching."
    value: "false"

  PUSH_TO_DOCKERHUB:
    description: "Push the built result to docker hub. Should be only set to true by schedules. Force builds all images."
    value: "false"

  PUSH_BUILT_IMAGE_TO_GITLAB:
    description: "Push the built image to gitlab. Force builds source and built image."
    value: "false"

  PUSH_DEV_IMAGE_TO_GITLAB:
    description: "Push the dev image to gitlab. Force builds all images."
    value: "false"

  DOCKERHUB_TAG:
    description: "Docker hub tag for this build."
    value: "dev"

  CUSTOM_APP_VENDOR:
    description: "Install one custom app via composer: vendor"
    value: "metaways"

  CUSTOM_APP_VERSION:
    description: "Install one custom app via composer: version"
    value: "dev-master"

  # install one custom app via composer: name
  # CUSTOM_APP_NAME default should be nothing

  # install one custom app via composer: git url
  # CUSTOM_APP_GIT_URL default should be nothing

  PHP_STAN_ANALYSES:
    description: "Enable php stan."
    value: "true"

  PHP_UNIT_ALL_TESTS_SOURCE:
    description: "Enable or disable php unit tests on source (with webpack) image."
    value: "true"

  PHP_UNIT_ALL_TESTS_BUILT:
    description: "Enable or disable php unit test on built (with built js, and clean files) image."
    value: "false"

  PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP:
    description: "Enable or disable run all test with ldap backend enabled. Does not effect or is evected by PHP_UNIT_ALL_TESTS_BUILT."
    value: "false"

  PHP_UNIT_SERVERTESTS:
    description: "Enable or disable server tests."
    value: "true"

  PHP_UNIT_SETUP_TESTS:
    description: "Enable or disable php unit setup tests."
    value: "false"

  PHP_UNIT_NOGITLABCI_TESTS_BUILT:
    description: "Run test with nogitlabci group (test know to not work in gitlab)."
    value: "false"

  PHP_UNIT_ALL_TESTS_SOURCE_PARALLEL:
    description: "Whether to run source test in parallel or not."
    value: "true"

  PHP_UNIT_TESTS_POSTFIXMULTIINSTANCE:
    description: "Whether to run a source test with the postfixmultiinstance backend."
    value: "false"

  JS_E2E_TEST_SOURCE:
    description: "Whether to run e2e test on source image"
    value: "false"

  JS_E2E_TEST_BUILT:
    description: "Whether to run e2e test on built image"
    value: "false"

  DATABASE_IMAGE:
    description: "Database image used by tests."
    value: "${UTIL_REGISTRY}/mariadb:10.4.1"

  REDIS_IMAGE:
    description: "Rdis image to use druing tests."
    value: "${UTIL_REGISTRY}/redis:5.0.5"

  PHPUNIT_FILTER:
    description: "Add a php unit filter to all php unit test jobs e.g. CashBook. This is used for customapp tests."
    value: ""

  TEST_WITH_HEALTH_CHECK:
    description: "test if tine20 /health api dose not return a 500"
    value: "false"
  
  RUN_ALL_TESTS:
    description: "Run all tests."
    value: "false"

  CHECK_PHP_VERSION:
    description: "Test if the image was build with the correct php version."
    value: "false"

  PHP_VERSION:
    description: "Php version to use."
    value: "7.3"
